### ISSUE TITLE
App runner times out when connecting to RDS instance

### ISSUE THREAD

**Issue by sefasenturk95** [aws/apprunner-roadmap#198]
So I try to spin up an app runner instance but every time it tries to run it throws a i/o timeout. I tried the following:
1. Made sure the security group is set up correctly and accepts the connections from/to the RDS instance
2. Made sure the RDS instance and app runner instance are in the same region
3. Made sure they are using the same VPC / connect to the correct VPC via the VPC connector (I am just using the default VPC in my region eu-west-1)
4. Set up an VPC endpoint for RDS using the interface.
5. Made the database publicly accessible

Here some screenshots of my setup:

**App Runner**
<img width="2466" alt="Screenshot 2023-06-22 at 09 13 42" src="https://github.com/aws/apprunner-roadmap/assets/3214653/e99c01a8-ecea-4b9d-b9e2-a8d20bffa55a">
<img width="1753" alt="Screenshot 2023-06-22 at 09 14 06" src="https://github.com/aws/apprunner-roadmap/assets/3214653/c60effe7-2198-4f46-ab89-5898ecdd1f76">

**VPC Subnets**
<img width="2306" alt="Screenshot 2023-06-22 at 09 17 59" src="https://github.com/aws/apprunner-roadmap/assets/3214653/bf886c5b-a4c0-4b63-b53e-9f06dd24c8aa">

**Security group**
<img width="1755" alt="Screenshot 2023-06-22 at 09 17 15" src="https://github.com/aws/apprunner-roadmap/assets/3214653/5b614754-fc52-40ed-8178-59e1b989234e">

**RDS Instance**
<img width="2147" alt="Screenshot 2023-06-22 at 09 18 58" src="https://github.com/aws/apprunner-roadmap/assets/3214653/6c8bc0bc-5e33-460d-8501-a368e47cc13b">

**VPC Endpoint**
<img width="2133" alt="Screenshot 2023-06-22 at 09 20 03" src="https://github.com/aws/apprunner-roadmap/assets/3214653/48ed16c6-1228-4fed-958f-a8c6c140f6c2">

And the error I get:
<img width="1704" alt="Screenshot 2023-06-22 at 09 23 58" src="https://github.com/aws/apprunner-roadmap/assets/3214653/b2d5de79-6ba0-4df3-9a34-2cb90a10a37d">

I am trying things for a couple days now and I cannot see it. I have exactly the same set up on another AWS account and there it seems to work. I am looking now for a couple of days I am not seeing it.. Anyone can point me in the right direction?

**Comment by richmungla** [comment]
@sefasenturk95 I had this same issue while deploying a keycloak instance 

So I haven't fully fixed my issue but I've taken some steps to debug 

I created a simple node js application that has two endpoints. One hello world, the other to test the db connection with the credentials I provide (hardcoded since its an image in a private repo that I will delete once done)

I tested that the node app can connect to the rds locally and in the container locally. The I pushed it to ECR and created an app runner instance. 

When testing this simple app the service deployed successfully and when testing the DB connection it worked :). This showed me that the issue is not my networking / vpc issue. So now I'm trying to figure out why keycloak specifically is refusing to connect but atleast i'm one step in the right direction. 

This may help you too, in debugging your issue 


while testing maybe allow your rds to be publicly accessible as you narrow down the issue

**Comment by kaitohattori** [comment]
I was facing same issue.

In my case, the cause was missing pass the TLS certificate.

After the set the certificate, the issue was resolved.
https://docs.aws.amazon.com/en_us/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

```
func registerTLS(certFilePath string, tlsKeyName string) {
	pem, err := os.ReadFile(certFilePath)
	if err != nil {
		log.Fatalln(err)
	}

	certPool := x509.NewCertPool()
	if ok := certPool.AppendCertsFromPEM(pem); !ok {
		log.Fatalln("failed to append pem.")
	}

	err = mysql.RegisterTLSConfig(tlsKeyName, &tls.Config{
		RootCAs: certPool,
	})
	if err != nil {
		log.Fatalln(err)
	}
}

```

```
dsn := "<user>:<password>@tcp(<host>:<port>)/<database>?charset=utf8mb4&parseTime=True&tls=<tlsKeyName>&loc=Local"
```
