### ISSUE TITLE
Cost for metrics scraping

### ISSUE THREAD

**Issue by biplovkc** [aws/apprunner-roadmap#69]
I have a app runner service running which does not have much traffic at the moment. Probably 10-20 request per day.
I was thinking of adding metrics endpoint for my dotnet application which would contain all sorts of metrics such as memory being used, number or request handled, request-response duration, etc.
These metrics would be scraped my services like prometheus probably every minute.
Since the metrics scraping would generate significant amount of extra request compared to my current total traffic, I was wondering how much cost increase this would result to. I use 1vcpu and 2GB ram runner at the moment.

**Comment by toricls** [comment]
Hi @biplovkc, thanks for reaching out to us for the question! I'm closing this issue since this is the place to gather and discuss roadmap items such as feature requests.

Regarding your question, you can create a support ticket in the AWS management console to get answered, or you can send me a DM via https://twitter.com/toricls to have further conversation on your question :)

Thanks!
